language: node_js

node_js: 
  - 8

install: 
  - npm install

test:
  - npm test

services:
  - postgresql

before_script:
  - psql -c 'create database storemanager;' -U postgres
  - psql -c "CREATE USER ezekiel WITH PASSWORD '123456';" -U postgres


after_success:
  - npm run coveralls